Release: v0.x
vtex-apps/shopback pull request #2
Opened 2019-09-30 18:01 UTC by juliomoreira

2019-09-30 18:03 UTC, juliomoreira reviewed
@klzns can you please review?

2019-09-30 18:04 UTC, juliomoreira commented
@saviofelixmuniz

2019-10-03 15:53 UTC, saviomuniz requested changes

2019-10-03 15:53 UTC, saviofelixmuniz commented on manifest.json
> +  "version": "0.0.0",
Versão 0.0.1
```suggestion
  "version": "0.0.1",
```

2019-10-03 15:54 UTC, saviomuniz approved these changes

2019-10-03 15:54 UTC, merged